name: Testing Framework

on:
  schedule: # schedule the job to run every hour
   - cron: '0 * * * *'
  
  workflow_dispatch:

  pull_request: ## temporary for debugging development purposes
    branches:
      - main

env:
  TF_VAR_aws_region: "eu-west-2"
  TF_VAR_aws_instance_type: "t3.large"
  TF_VAR_aws_ami_owners: '["125523088429"]'
  TF_VAR_aws_ami_name: '["Fedora-Cloud-Base-*"]'
  TF_VAR_aws_volume_size: 100
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_provision_script: ../main/.github/scripts/provision.sh
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # AWS_DEFAULT_REGION: "eu-west-2"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          path: main

      - name: Checkout terraform module
        id: checkout-module
        uses: actions/checkout@v4.1.1
        with:
          repository: containers/terraform-test-environment-module
          path: terraform-test-environment-module
          ref: 'main'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Init Terraform
        run: terraform init
        working-directory: terraform-test-environment-module

      - name: Spin Test Environment
        id: up
        run: terraform apply -auto-approve -lock=false
        working-directory: terraform-test-environment-module
      
      - name: Terraform Output
        id: terraform-output
        run: |
          echo "id=$(terraform output id | xargs)" >> $GITHUB_OUTPUT
          echo "url=$(terraform output host | xargs)" >> $GITHUB_OUTPUT
        working-directory: terraform-test-environment-module

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: ./main/recipes/natural_language_processing/chatbot
        run: make install

      - name: Wait for the user data script to finish
        run: sleep 240

      - name: Run Integration Tests
        working-directory: ./main/recipes/natural_language_processing/chatbot
        run: make URL=${{ steps.terraform-output.outputs.url }} integration_tests
 
      - name: Destroy Test Environment
        id: down
        if: always()
        run: terraform destroy -auto-approve -lock=false
        working-directory: terraform-test-environment-module

      - name: Publish Job Results to Slack
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "link",
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "text": "${{ github.workflow }} workflow status: ${{ job.status }}",
                          "style": {
                            "bold": true
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
